import sys
from pathlib import Path

# Ensure project root is on sys.path so top-level modules (like mongo_logging) can be imported
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from mongo_logging import log_alert

# Create a minimal fake features record (list of dicts)
features = [{'src_ip': '10.0.0.123', 'dst_ip': '192.168.1.5', 'protocol': 'TCP'}]

predictions = [1]  # placeholder
explanation = 'Test alert generated by emit_test_alert'

if __name__ == '__main__':
    log_alert(features, predictions, explanation, attack_type='Test', gemini_rules={'iptables': 'iptables -A INPUT -s 10.0.0.123 -j DROP'}, severity='High')
    print('Test alert inserted')
